config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'


  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :users, only: [:show, :create, :edit, :update]


  resources :posts, except: [:destroy] do

    member do 
      post 'vote'
    end 
  resources :comments, only: [:create] do
    member do
      post 'vote'
    end 
  end 
end   
  resources :categories, only: [:new, :create, :show]
end

app/models/Comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
   has_many :votes, as: :voteable

  validates :body, presence: true

  def total_votes
  self.up_votes - self.down_votes
end 

def up_votes
  self.votes.where(vote: true).size
end 

def down_votes
  self.votes.where(vote: false).size
end 

end 

app/models/Post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments 
  has_many :post_categories

  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true 
  validates :url, presence: true, uniqueness: true 

def total_votes
  self.up_votes - self.down_votes
end 

def up_votes
  self.votes.where(vote: true).size
end 

def down_votes
  self.votes.where(vote: false).size
end 

end 

app/models/Post_Category.rb
class PostCategory < ActiveRecord::Base 
  belongs_to :post
  belongs_to :category 
end 

app/models/User.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :votes 

  has_secure_password validations: false 
  validates :user_name, presence: true, uniqueness: true 
  validates :password, presence: true, on: :create, length: {minimum: 4}

end 

app/models/Vote.rb
class Vote < ActiveRecord::Base

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :voteable, polymorphic: true 

validates_uniqueness_of :creator, scope: [:voteable_id, :voteable_type ]

end 

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in? #makes the methods available in all views and in all controllers

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end 

  def logged_in?
    !!current_user
  end 

  def require_user
    if !logged_in?
      flash[:error] = "You must log in to do that"
      redirect_to root_path
    end 
  end 



end

app/controllers/categories_controller.rb
#categories controller
class CategoriesController < ApplicationController
before_action :require_user, only: [:new, :create]

def show
  @category = Category.find(params[:id])
end 

def new
  @category = Category.new 
end 

def create
  @category = Category.new(category_params)

  if @category.save
    flash[:notice] = "Category has been created"
    redirect_to root_path
  else
    render 'new'
  end 
end 

private

def category_params
  params.require(:category).permit(:name)
end 

end 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :require_user
def create 
  
  @post = Post.find(params[:post_id])
  @comment = Comment.new(comment_params)
  @comment.post = @post 
  @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Your comment has been created"
      redirect_to posts_path(@post) 

    else 
      render 'posts/show' 
    end 

  end 

  def vote
    comment = Comment.find(params[:id])

    comment = Vote.create(voteable: comment, creator: current_user, vote: params[:vote])
    
    if comment.valid? 
    flash[:notice] = "Your vote was counted" 
    redirect_to  :back
    
    else
    flash[:error] = "You can only vote once"
    redirect_to :back
    end 
  end 

  private

  def comment_params
    params.require(:comment).permit(:body)
    
  end

end 
 

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :set_post, only: [:show, :edit, :update, :vote]
before_action :require_user, except: [:show, :index]

  def index
    @posts = Post.all.sort_by {|x| x.total_votes }.reverse
  end

  def show
    @comment = Comment.new
  end 

  def new
    @post = Post.new 
    #new_post 
  end 

  def create
   
  @post = Post.new(post_params)
  @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post has been created"
      redirect_to posts_path 

    else  
      render 'new' 
  end 

  end 

  def edit; end 

  def vote
    
    vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
    
    if vote.valid?  
    flash[:notice] = "Your vote was counted" 
    redirect_to  :back

    else
      flash[:error] = "You can only vote once"
      redirect_to :back
    end 
  end 

  def update
  

    if @post.update(post_params)
      flash[:notice] = "The post was updated"
      redirect_to post_path(@post)

    else
      render :edit
    
    end 

  end 

def set_post 
  
    @post = Post.find(params[:id])

  end 

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
    
  end

   

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end 

  def create
  user = User.find_by(user_name: params[:username])


    if user && user.authenticate(params[:password])
      session[:user_id] = user.id 
      flash[:notice] = "Weclome #{user.user_name}, you have logged in successfully"
      redirect_to root_path

    else 
    flash[:error] = "Username or Password is incorrect"
    render 'new'
    end 
  end 

  def destroy
    session[:user_id] = nil 
    flash[:notice] = "You have logged out"
    redirect_to root_path
  end 


end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update]
before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end 

  def create
    @user = User.new(user_params)
  
    if @user.save
     
      session[:user_id] = @user.id 
      flash[:notice] = "Weclome #{@user.user_name}, you have registered and logged in successfully"
      redirect_to root_path

      else  
      render 'new'
      end 

  end 

  def update

      if @user.update(user_params)
     
      session[:user_id] = @user.id 
      flash[:notice] = "#{@user.user_name}, your profile has been updated"
      redirect_to root_path

      else  
      render 'edit'
      end 

  end 

  def edit; end 

  def show; end 

  def user_params
    params.require(:user).permit(:user_name, :password)  
  end

  def set_user
    @user = User.find(params[:id])
  end 

  def require_same_user
    if current_user != @user
      flash[:error] = "You do not have permisions to edit a user other than yourself"
      redirect_to root_path
    end 
  end 

end 

app/helpers/application_helper.rb
module ApplicationHelper
  
  def fix_url (string)
    string.starts_with?('http://') ? string : "http://#{string}"
  end 

  def display_datetime(dt)
    dt.strftime("%m/%d/%Y %l:%M%P %Z")


  end 
end

app/views/categories/_category.html.erb
<span class ="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "New Category"%>
<%= render 'shared/errors', obj: @category %>  

<div class='well' %> 
<%= form_for @category do |cat| %> 

  <div class='control-group'> 
      <%= cat.label :name %> 
      <%= cat.text_field :name%> 
  </div> 
  <%= cat.submit "Create Category", class: 'btn btn-success' %> 

  <% end %> 
</div> 

app/views/categories/show.html.erb
<% header = link_to('All Posts ', posts_path) + " &raquo; Showing Category: #{@category.name}".html_safe%> 

<%= render 'shared/content_title', title: header %> 

<% @category.posts.each do |post| %> 

<%= render 'posts/post', post: post %> 

<% end %> 

app/views/comments/_comment.html.erb
<div class ="well span8">
  <em>"<%= comment.body %>"</em>
  <% if show_post %> 
  on <%= link_to comment.post.title, post_path(comment.post) %> 
  <% end %> 
</br> 
<span class='quiet'>by </span> <%= comment.creator.user_name %> 
<small>at <%= display_datetime(comment.created_at) %></small> 

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "FindUrRide!!", root_path, :class => 'brand' %>
  </li>
</ul>

<div class='btn-group nav_item'>
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class='caret'></span> 
    <%end%> 

    <ul class='dropdown-menu'>
        <% Category.all.each do |category| %> 
        <li><%= link_to category.name, category_path(category) %>  </li> 
        <% end %>

        <% if logged_in? %> 
        <li class='divider'></li> 
        <li>
          <%= link_to(new_category_path) do %> 
            <i class="icon-plus"></i>
            New Category
            <% end %> 
        </li> 
      <% end %> 
    </ul>  
</div> 


<% if logged_in? %> 
  <div class='nav_item'>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %> 
  </div> 

  <div class='btn-group nav_item'>
  <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    <%= current_user.user_name %> 
     <span class='caret'></span> 
  <%end%> 

    <ul class='dropdown-menu'>

        <li>
          <%= link_to edit_user_path(current_user) do %>
          <i class ='icon-pencil'></i> 
          edit profile
          <% end %>   

        </li> 
        

        <li>
          <%= link_to user_path(current_user) do %>
          <i class ='icon-user'></i> 
          view profile
          <% end %>   

        </li> 
     
        <li class='divider'></li> 
        <li>
          <%= link_to(logout_path) do %> 
            <i class="icon-circle-arrow-left"></i>
            logout
            <% end %> 
        </li> 
      </ul> 
  </div> 

  

<% else %> 
 <div class='nav_item'>
  <%= link_to 'Register', register_path, class: 'btn btn-success btn-small' %> 
  </div> 

  <div class='nav_item'>
  <%= link_to 'Log in', login_path, class: 'btn btn-small' %> 
  </div> 

<% end %> 

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>  

<div class='well' >

<%= form_for @post do |form| %> 

  <div class ='control-group'> 
  <%= form.label :title %> 
  <%= form.text_field :title %> 
  </div> 

  <div class ='control-group'> 
  <%= form.label :url, "URL", class: "col-md-4 control-label" %> 
  <%= form.text_field :url %>
  </div> 

  <div class ='control-group'> 
  <%= form.label :description %> 
  <%= form.text_area :description, rows: 5, placeholder: "Type your post here" %> 
  </div> 
  <div class = 'control-group'>
    <%= form.label 'Categories' %> 
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %> 
    <%= cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
  
    <% end %> 
    </div>
  <%= form.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: "btn btn-primary") %> 
<% end %> 
</div>

app/views/posts/_post.html.erb
<div class ="row">
  <% if logged_in? %> 
  <div class='span0 well' text-center>  
    <%= link_to vote_post_path(post, vote: true), method: 'post' do %> 
    <i class = 'icon-arrow-up'></i>
    <%end%> 
    </br>
    <%= post.total_votes %> votes
  </br> 
    <%= link_to vote_post_path(post, vote: false), method: 'post' do %> 
    <i class = 'icon-arrow-down'></i>
    <%end%> 
   </div> 
   <%end%> 
  <div class='span8 well'>

    <%= render post.categories %> 
    
    <h4><%= link_to post.title, fix_url(post.url) %> </h4>
    <p> <%= post.description %> </p>
    <p>
      <span class = 'quiet'>posted by </span> <%= link_to post.creator.user_name, user_path(post.creator) %> 
      <small>at <%= display_datetime(post.created_at) %></small>

    </p>
    <small>
      <span> 
        <%= link_to("edit post", edit_post_path(post))%>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %> 

      </span>
    </small>
  </div>
</div> 

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Post' %> 
<%= render 'form' %> 

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Callers" %>

<% @posts.each do |post| %>  
<%= render 'post', post: post %> 
<% end %> 

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create New Post' %> 
<%= render 'form' %> 

app/views/posts/show.html.erb
<% if logged_in? %> 
<p class = 'pull-right'>
[<%= link_to("edit post", edit_post_path(@post))%>]
</p>
<% end %> 
<p>

  <%= render @post.categories %> 
</p>  

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %> 
</p>
<hr/> 

<%= render 'shared/errors', obj: @comment %>  

<%= form_for [@post, @comment] do |form| %> 
<% if logged_in? %> 
  <div class ='control-group'> 
  <%= form.label 'Comments' %> 
  <%= form.text_area :body, placeholder: "Type your comment here"  %> 
  </div> 

  <%= form.submit "Create Comment", class: "btn btn-primary" %> 

  <% end %> 
<% end %> 

<h2>Comments:</h2>

<% @post.comments.each do |c| %> 
  <div class ="row">
    <% if logged_in? %> 
    <div class='span0 well text-center'> 
       <%= link_to vote_post_comment_path(@post, c, vote: true), method: 'post' do %> 
    <i class = 'icon-arrow-up'></i>
    <%end%> 
    </br>
    <%= c.total_votes %> votes
  </br> 
    <%= link_to vote_post_comment_path(@post, c, vote: false), method: 'post' do %> 
    <i class = 'icon-arrow-down'></i>
    <%end%> 
    </div> 
    <% end %> 

    <div class='spann8 well'>  
        <en>"<%= c.body %>"</en> 
      </br>
    <span class = 'quiet'>by </span> <%= link_to c.creator.user_name, ' ' %> 
    <small>at <%= display_datetime(c.created_at) %></small>
    </div>
  </div>
<%end %> 

app/views/shared/_content_title.html.erb
<p class='lead'> 
  <h3><%= title %></h3> 
  <hr/> 
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %> 
  <div class='row'>
    <div class = 'alert alert-error span8'>
      <h5> Please fix the following <h5> 
        
        <% obj.errors.full_messages.each do |msg| %> 
        <li> <%= msg %> </li> 
        <%end%> 
    </div>
  </div> 
<%end%> 

app/views/users/_form.html.erb
<div class='well' >

<%= form_for @user do |form| %> 
<%= render 'shared/errors', obj: @user %> 

  <div class ='control-group'> 
  <%= form.label :Username %> 
  <%= form.text_field :user_name %> 
  </div> 

  <div class ='control-group'> 
  <%= form.label :Password, "Password", class: "col-md-4 control-label" %> 
  <%= form.password_field :password %>
  </div> 

  <%= form.submit(@user.new_record? ? 'Register User' : 'Update User', class: "btn btn-primary")%> 

  <% end %> 

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit User Profile' %> 
<%= render 'form' %> 

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register User' %> 
<%= render 'form' %> 

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.user_name}" %> 

<div class='well'> 

  <dl class='dl-horizontal'> 
    <dt> Username: </dt> 
      <dd> <%= @user.user_name %> </dd> 
    </dl> 
</div> 

    <h5><%= @user.user_name %> Activity</h5> 
    <ul class ='nav nav-tabs'> 
     <li class ='<%= 'active' if params[:clicked].nil? %>' >
        <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %> 
      </li> 
      <li class ='<%= 'active' if params[:clicked] == 'comments'%>' >
        <%= link_to "Comments(#{@user.comments.size})", user_path(@user, clicked: 'comments') %>
      </li>
    </ul> 

    <% if params[:clicked].nil? %> 

      <% @user.posts.each do |p| %> 
      <%= render 'posts/post', post: p %>  
      <%end%> 

    <% elsif params[:clicked] == 'comments' %> 
    <% @user.comments.each do |comment| %> 
      <%= render 'comments/comment', comment: comment, show_post: true %> 
      <%end%>

    <% end %> 



    